-- MySQL Script generated by MySQL Workbench
-- Mon Nov 18 16:24:12 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`passenger`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`passenger` (
  `psg_id` INT NOT NULL COMMENT 'Identification card/ passport',
  `psg_type` INT NOT NULL COMMENT 'Domestic = 0/ international = 1',
  `last_name` VARCHAR(45) NOT NULL,
  `middle_name` VARCHAR(45) NOT NULL,
  `first_name` VARCHAR(45) NOT NULL,
  `gender` INT NOT NULL COMMENT 'female = 1 / male = 1',
  PRIMARY KEY (`psg_id`, `psg_type`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ticket`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ticket` (
  `ticket_no` INT NOT NULL,
  `psg_id` INT NOT NULL,
  `psg_type` INT NOT NULL,
  `ticket_type` INT NOT NULL COMMENT 'economy = 0 / business = 1 / first class = 2',
  `ticket_price` FLOAT NOT NULL,
  `baggage_price` FLOAT NOT NULL COMMENT 'The additional baggage price',
  PRIMARY KEY (`ticket_no`),
  INDEX `fk_ticket_passenger_idx` (`psg_id` ASC, `psg_type` ASC) VISIBLE,
  CONSTRAINT `fk_ticket_passenger`
    FOREIGN KEY (`psg_id` , `psg_type`)
    REFERENCES `mydb`.`passenger` (`psg_id` , `psg_type`)
    ON DELETE NO ACTION
    


-- -----------------------------------------------------
-- Table `mydb`.`airport`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`airport` (
  `airport_code` INT NOT NULL,
  `airport_name` VARCHAR(45) NOT NULL,
  `city_code` INT NOT NULL,
  `country_code` INT NOT NULL,
  PRIMARY KEY (`airport_code`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`aircraft_model`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`aircraft_model` (
  `aircraft_model_id` INT NOT NULL,
  `aircraft_model_name` VARCHAR(45) NOT NULL,
  `first_seats` INT NOT NULL COMMENT 'The sum number of the first seats',
  `business_seats` INT NOT NULL,
  `economy_seats` INT NOT NULL,
  PRIMARY KEY (`aircraft_model_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`aircraft`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`aircraft` (
  `aircraft_id` INT NOT NULL,
  `aircraft_model_id` INT NOT NULL,
  `aircraft_year` INT NOT NULL,
  PRIMARY KEY (`aircraft_id`),
  INDEX `fk_aircraft_aircraft_model1_idx` (`aircraft_model_id` ASC) VISIBLE,
  CONSTRAINT `fk_aircraft_aircraft_model1`
    FOREIGN KEY (`aircraft_model_id`)
    REFERENCES `mydb`.`aircraft_model` (`aircraft_model_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`route`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`route` (
  `route_id` INT NOT NULL,
  `departure` INT NOT NULL,
  `destination` INT NOT NULL,
  `distance` FLOAT NOT NULL,
  PRIMARY KEY (`route_id`),
  INDEX `fk_route_airport1_idx` (`departure` ASC) VISIBLE,
  INDEX `fk_route_airport2_idx` (`destination` ASC) VISIBLE,
  CONSTRAINT `fk_route_airport1`
    FOREIGN KEY (`departure`)
    REFERENCES `mydb`.`airport` (`airport_code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_route_airport2`
    FOREIGN KEY (`destination`)
    REFERENCES `mydb`.`airport` (`airport_code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`flight`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`flight` (
  `flight_no` INT NOT NULL,
  PRIMARY KEY (`flight_no`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`flight_legs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`flight_legs` (
  `flight_no` INT NOT NULL,
  `leg_no` INT NOT NULL,
  `dep_time` DATETIME NOT NULL,
  `route_id` INT NOT NULL,
  `arr_time` DATETIME NOT NULL,
  INDEX `fk_flight_legs_route1_idx` (`route_id` ASC) VISIBLE,
  PRIMARY KEY (`flight_no`, `leg_no`),
  CONSTRAINT `fk_flight_legs_route1`
    FOREIGN KEY (`route_id`)
    REFERENCES `mydb`.`route` (`route_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_flight_legs_flight1`
    FOREIGN KEY (`flight_no`)
    REFERENCES `mydb`.`flight` (`flight_no`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`leg_instance`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`leg_instance` (
  `flight_no` INT NOT NULL,
  `leg_no` INT NOT NULL,
  `date_of_travel` DATE NOT NULL,
  `dep_time` DATETIME NOT NULL,
  `arr_time` DATETIME NOT NULL,
  `aircraft_id` INT NOT NULL,
  PRIMARY KEY (`flight_no`, `leg_no`, `date_of_travel`),
  INDEX `fk_leg_instance_aircraft1_idx` (`aircraft_id` ASC) VISIBLE,
  CONSTRAINT `fk_leg_instance_aircraft1`
    FOREIGN KEY (`aircraft_id`)
    REFERENCES `mydb`.`aircraft` (`aircraft_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_leg_instance_flight_legs1`
    FOREIGN KEY (`flight_no` , `leg_no`)
    REFERENCES `mydb`.`flight_legs` (`flight_no` , `leg_no`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`seat`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`seat` (
  `seat_no` INT NOT NULL,
  `flight_no` INT NOT NULL,
  `leg_no` INT NOT NULL,
  `date_of_travel` DATE NOT NULL,
  PRIMARY KEY (`seat_no`, `flight_no`, `leg_no`, `date_of_travel`),
  INDEX `fk_seat_leg_instance1_idx` (`flight_no` ASC, `leg_no` ASC, `date_of_travel` ASC) VISIBLE,
  CONSTRAINT `fk_seat_leg_instance1`
    FOREIGN KEY (`flight_no` , `leg_no` , `date_of_travel`)
    REFERENCES `mydb`.`leg_instance` (`flight_no` , `leg_no` , `date_of_travel`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`reservation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`reservation` (
  `rev_id` INT NOT NULL,
  `ticket_no` INT NOT NULL,
  `flight_no` INT NOT NULL,
  `leg_no` INT NOT NULL,
  `date_of_travel` DATE NOT NULL,
  `seat_no` INT NOT NULL,
  PRIMARY KEY (`rev_id`),
  INDEX `fk_reservation_ticket1_idx` (`ticket_no` ASC) VISIBLE,
  INDEX `fk_reservation_seat1_idx` (`flight_no` ASC, `leg_no` ASC, `seat_no` ASC, `date_of_travel` ASC) VISIBLE,
  CONSTRAINT `fk_reservation_ticket1`
    FOREIGN KEY (`ticket_no`)
    REFERENCES `mydb`.`ticket` (`ticket_no`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_reservation_seat1`
    FOREIGN KEY (`flight_no` , `leg_no` , `seat_no` , `date_of_travel`)
    REFERENCES `mydb`.`seat` (`flight_no` , `leg_no` , `seat_no` , `date_of_travel`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ground_cost`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ground_cost` (
  `flight_no` INT NOT NULL,
  `leg_no` INT NOT NULL,
  `date_of_travel` DATE NOT NULL,
  `wearing` FLOAT NOT NULL,
  `maintenance` FLOAT NOT NULL,
  `airport_usage_fee` FLOAT NOT NULL,
  PRIMARY KEY (`flight_no`, `leg_no`, `date_of_travel`),
  CONSTRAINT `fk_ground_cost_leg_instance1`
    FOREIGN KEY (`flight_no` , `leg_no` , `date_of_travel`)
    REFERENCES `mydb`.`leg_instance` (`flight_no` , `leg_no` , `date_of_travel`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`flight_cost`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`flight_cost` (
  `flight_no` INT NOT NULL,
  `leg_no` INT NOT NULL,
  `fuel` FLOAT NOT NULL,
  `food` FLOAT NOT NULL,
  PRIMARY KEY (`flight_no`, `leg_no`),
  CONSTRAINT `fk_fly_cost_flight_legs1`
    FOREIGN KEY (`flight_no` , `leg_no`)
    REFERENCES `mydb`.`flight_legs` (`leg_no` , `flight_no`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`job`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`job` (
  `job_id` INT NOT NULL,
  `job_name` VARCHAR(45) NOT NULL,
  `salary` FLOAT NOT NULL,
  PRIMARY KEY (`job_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`staff`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`staff` (
  `staff_id` INT NOT NULL,
  `job_id` INT NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `middle_name` VARCHAR(45) NOT NULL,
  `first_name` VARCHAR(45) NOT NULL,
  `gender` INT NOT NULL COMMENT 'Male = 0/ famale = 1',
  `phone_no` INT NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `birthday` DATE NOT NULL,
  PRIMARY KEY (`staff_id`),
  INDEX `fk_staff_job1_idx` (`job_id` ASC) VISIBLE,
  CONSTRAINT `fk_staff_job1`
    FOREIGN KEY (`job_id`)
    REFERENCES `mydb`.`job` (`job_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`crew`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`crew` (
  `crew_id` INT NOT NULL,
  `flight_no` INT NOT NULL,
  `date_of_travel` DATE NOT NULL,
  PRIMARY KEY (`crew_id`, `flight_no`, `date_of_travel`),
  INDEX `fk_crew_leg_instance1_idx` (`flight_no` ASC, `date_of_travel` ASC) VISIBLE,
  CONSTRAINT `fk_crew_staff1`
    FOREIGN KEY (`crew_id`)
    REFERENCES `mydb`.`staff` (`staff_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_crew_leg_instance1`
    FOREIGN KEY (`flight_no` , `date_of_travel`)
    REFERENCES `mydb`.`leg_instance` (`flight_no` , `date_of_travel`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

